project/api/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^fs/status$', views.FileStatusView.as_view(), name='fs_status'),
    url(r'^fs/(?P<filename>[0-9a-f]*)$', views.FileView.as_view(), name='fs_status'),
    url(r'^jobs/take$', views.JobTakeView.as_view(), name='take_job'),
    url(r'^jobs/(?P<job_id>\d+)/result$', views.JobPutResultView.as_view()),
    url(r'^jobs/(?P<job_id>\d+)/state$', views.JobPutStateView.as_view()),
    url(r'^compiler-settings$', views.CompilerSettingsView.as_view()),
    url(r'^plagiarism/take$', views.PlagiarismTakeView.as_view()),
    url(r'^plagiarism/put$', views.PlagiarismPutView.as_view()),
    url(r'^sleep$', views.SleepView.as_view()),
    url(r'^printing$', views.PrintingView.as_view()),
    url(r'^printing/(?P<printout_id>\d+)$', views.PrintingDoneView.as_view()),

    url(r'^queue/$', views.QueueView.as_view(), name='queue')
]

project/irunner2/urls.py
from django.conf.urls import include, url
#from django.contrib import admin
import common.views
from django_js_reverse.views import urls_js
from django.views.decorators.cache import cache_page


urlpatterns = [
    url(r'^$', common.views.home, name='home'),
    url(r'^language/$', common.views.language, name='language'),
    url(r'^feedback/', include('feedback.urls', namespace='feedback')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^i18n/', include('django.conf.urls.i18n'), name='set_language'),
    url(r'^storage/', include('storage.urls', namespace='storage')),
    url(r'^problems/', include('problems.urls', namespace='problems')),
    url(r'^compilers/', include('proglangs.urls', namespace='proglangs')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^', include('solutions.urls', namespace='solutions')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^contests/', include('contests.urls', namespace='contests')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^quiz-demo/', include('quizdemo.urls', namespace='quizdemo')),
    url(r'^about/', common.views.about, name='about'),
    url('^', include('cauth.urls')),
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^jsreverse/$', cache_page(3600)(urls_js), name='js_reverse'),
    url(r'^hall-of-fame/$', common.views.HallOfFameView.as_view(), name='hall_of_fame'),
    url(r'^activity/$', common.views.ActivityView.as_view(), name='activity'),
]

handler403 = 'common.views.error403'

project/problems/urls.py
from django.conf.urls import include, url

from . import views

problem_urlpatterns = [
    url(r'^$', views.ProblemOverviewView.as_view(), name='overview'),
    url(r'^statement/(?P<filename>.+)?$', views.ProblemStatementView.as_view(), name='statement'),

    url(r'^tests/$', views.ProblemTestsView.as_view(), name='tests'),
    url(r'^tests/browse/$', views.ProblemBrowseTestsView.as_view(), name='browse_tests'),
    url(r'^tests/(?P<test_number>[0-9]+)/$', views.ProblemTestsTestView.as_view(), name='show_test'),
    url(r'^tests/upload/$', views.ProblemTestsUploadArchiveView.as_view(), name='upload_archive'),
    url(r'^tests/new/$', views.ProblemTestsNewView.as_view(), name='new_test'),
    url(r'^tests/(?P<test_number>[0-9]+)/edit/$', views.ProblemTestsTestEditView.as_view(), name='edit_test'),
    url(r'^tests/(?P<test_number>[0-9]+)/delete/$', views.ProblemTestsDeleteView.as_view(), name='delete_test'),
    url(r'^tests/(?P<test_number>[0-9]+)/image/(?P<filename>.+)$', views.ProblemTestsTestImageView.as_view(), name='test_image'),
    url(r'^tests/batch/set/time-limit/$', views.ProblemTestsSetTimeLimitView.as_view(), name='tests_mass_time_limit'),
    url(r'^tests/batch/set/memory-limit/$', views.ProblemTestsSetMemoryLimitView.as_view(), name='tests_mass_memory_limit'),
    url(r'^tests/batch/set/points/$', views.ProblemTestsSetPointsView.as_view(), name='tests_mass_points'),
    url(r'^tests/batch/delete/$', views.ProblemTestsBatchDeleteView.as_view(), name='tests_mass_delete'),

    url(r'^tests/open/input-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='input', download=False), name='test_input_open'),
    url(r'^tests/download/input-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='input', download=True), name='test_input_download'),
    url(r'^tests/open/answer-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='answer', download=False), name='test_answer_open'),
    url(r'^tests/download/answer-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='answer', download=True), name='test_answer_download'),

    url(r'^solutions/$', views.ProblemSolutionsView.as_view(), name='solutions'),
    url(r'^solutions/process/$', views.ProblemSolutionsProcessView.as_view(), name='solutions_process'),

    url(r'^files/$', views.ProblemFilesView.as_view(), name='files'),
    url(r'^files/data/(?P<file_id>[0-9]+)/open/(?P<filename>.+)$', views.ProblemFilesFileOpenView.as_view(), name='data_file_open'),
    url(r'^files/data/(?P<file_id>[0-9]+)/download/(?P<filename>.+)$', views.ProblemFilesFileOpenView.as_view(download=True), name='data_file_download'),
    url(r'^files/data/(?P<file_id>[0-9]+)/edit/$', views.ProblemFilesDataFileEditView.as_view(), name='data_file_edit'),
    url(r'^files/data/(?P<file_id>[0-9]+)/delete/$', views.ProblemFilesDataFileDeleteView.as_view(), name='data_file_delete'),
    url(r'^files/data/new/$', views.ProblemFilesDataFileNewView.as_view(), name='data_file_new'),

    url(r'^files/source/(?P<file_id>[0-9]+)/open/(?P<filename>.+)$', views.ProblemFilesSourceFileOpenView.as_view(), name='source_file_open'),
    url(r'^files/source/(?P<file_id>[0-9]+)/download/(?P<filename>.+)$', views.ProblemFilesSourceFileOpenView.as_view(download=True), name='source_file_download'),
    url(r'^files/source/(?P<file_id>[0-9]+)/edit/$', views.ProblemFilesSourceFileEditView.as_view(), name='source_file_edit'),
    url(r'^files/source/(?P<file_id>[0-9]+)/delete/$', views.ProblemFilesSourceFileDeleteView.as_view(), name='source_file_delete'),
    url(r'^files/source/new/$', views.ProblemFilesSourceFileNewView.as_view(), name='source_file_new'),

    url(r'^tex/$', views.ProblemTeXView.as_view(), name='tex'),
    url(r'^tex/render/$', views.ProblemTeXRenderView.as_view(), name='tex_render'),
    url(r'^tex/new/statement/$', views.ProblemTeXNewStatementView.as_view(), name='tex_new_statement'),
    url(r'^tex/(?P<file_id>[0-9]+)/$', views.ProblemTeXEditView.as_view(), name='edit_tex'),
    url(r'^tex/(?P<file_id>[0-9]+)/(?P<filename>.+)$', views.ProblemTeXEditRelatedFileView.as_view()),

    url(r'^challenges/$', views.ProblemChallengesView.as_view(), name='challenges'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/$', views.ProblemChallengeView.as_view(), name='challenge'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/add-test/$', views.ProblemChallengeAddTestView.as_view(), name='challenge_add_test'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/status/json/$', views.ProblemChallengeJsonView.as_view(), name='challenge_status_json'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/open/(?P<resource_id>[0-9a-f]*)/(?P<filename>[a-z0-9\-]+)\.txt$', views.ProblemChallengeDataView.as_view(download=False), name='challenge_data_open'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/download/(?P<resource_id>[0-9a-f]*)/(?P<filename>[a-z0-9\-]+)\.txt$', views.ProblemChallengeDataView.as_view(download=True), name='challenge_data_download'),
    url(r'^challenges/new/$', views.ProblemNewChallengeView.as_view(), name='new_challenge'),

    url(r'^rejudges/$', views.ProblemRejudgesView.as_view(), name='rejudges'),

    url(r'^submit/$', views.ProblemSubmitView.as_view(), name='submit'),
    url(r'^submission/(?P<solution_id>[0-9]+)/$', views.ProblemSubmissionView.as_view(), name='submission'),
    url(r'^folders/$', views.ProblemFoldersView.as_view(), name='folders'),
    url(r'^name/$', views.ProblemNameView.as_view(), name='name'),
    url(r'^properties/$', views.ProblemPropertiesView.as_view(), name='properties'),
    url(r'^pictures/$', views.ProblemPicturesView.as_view(), name='pictures'),
    url(r'^validator/$', views.ProblemValidatorView.as_view(), name='validator'),
    url(r'^delete/$', views.ProblemDeleteView.as_view(), name='delete'),
]

urlpatterns = [
    url(r'^tree/$', views.ShowTreeView.as_view(), name='show_tree'),
    url(r'^tree/(?P<folder_id>[0-9]+)/$', views.ShowTreeFolderView.as_view(), name='show_tree_folder'),
    url(r'^tree/(?P<folder_id>[0-9]+)/json/$', views.ShowTreeFolderJsonView.as_view(), name='show_tree_folder_json'),

    url(r'^(?P<problem_id>[0-9]+)/', include(problem_urlpatterns)),

    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/$', views.ShowFolderView.as_view(), name='show_folder'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/new/folder/$', views.CreateFolderView.as_view(), name='create_folder'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/new/problem/$', views.CreateProblemView.as_view(), name='create_problem'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/properties/$', views.UpdateFolderView.as_view(), name='folder_properties'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/delete/$', views.DeleteFolderView.as_view(), name='delete_folder'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/import-from-polygon/$', views.ImportFromPolygonView.as_view(), name='import_from_polygon'),

    url(r'^search/$', views.SearchView.as_view(), name='search'),

    url(r'^tex/$', views.TeXView.as_view(), name='tex_playground'),
    url(r'^tex/render/$', views.TeXRenderView.as_view(), name='tex_playground_render'),
]

project/solutions/urls.py
from django.conf.urls import include, url

from . import views

solutions_urlpatterns = [
    url(r'^$', views.SolutionListView.as_view(), name='list'),

    url(r'^(?P<solution_id>[0-9]+)/$', views.SolutionMainView.as_view(), name='main'),
    url(r'^(?P<solution_id>[0-9]+)/source/$', views.SolutionSourceView.as_view(), name='source'),
    url(r'^(?P<solution_id>[0-9]+)/log/$', views.SolutionLogView.as_view(), name='log'),
    url(r'^(?P<solution_id>[0-9]+)/tests/$', views.SolutionTestsView.as_view(), name='tests'),
    url(r'^(?P<solution_id>[0-9]+)/runs/$', views.SolutionJudgementsView.as_view(), name='judgements'),
    url(r'^(?P<solution_id>[0-9]+)/attempts/$', views.SolutionAttemptsView.as_view(), name='attempts'),
    url(r'^(?P<solution_id>[0-9]+)/plagiarism/$', views.SolutionPlagiarismView.as_view(), name='plagiarism'),
    url(r'^(?P<solution_id>[0-9]+)/status/json/$', views.SolutionStatusJsonView.as_view(), name='status_json'),

    url(r'^(?P<solution_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/$', views.SolutionTestCaseResultView.as_view(), name='test_case_result'),
    url(r'^(?P<solution_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/(?P<mode>input|output|answer|stdout|stderr)\.txt$', views.SolutionTestCaseResultDataView.as_view(), name='test_data'),
    url(r'^(?P<solution_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/images/(?P<filename>.*)$', views.SolutionTestCaseResultImageView.as_view(), name='test_image'),

    url(r'^(?P<solution_id>[0-9]+)/source/open/(?P<filename>.*)$', views.SolutionSourceOpenView.as_view(), name='source_open'),
    url(r'^(?P<solution_id>[0-9]+)/source/download/(?P<filename>.*)$', views.SolutionSourceDownloadView.as_view(), name='source_download'),

    url(r'^delete/$', views.DeleteSolutionsView.as_view(), name='delete'),

    url(r'^compare/$', views.CompareSolutionsView.as_view(), name='compare'),
]

judgements_urlpatterns = [
    url(r'^$', views.JudgementListView.as_view(), name='judgement_list'),
    url(r'^(?P<judgement_id>[0-9]+)/$', views.JudgementView.as_view(), name='show_judgement'),
    url(r'^(?P<judgement_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/$', views.JudgementTestCaseResultView.as_view(), name='judgement_testcaseresult'),
    url(r'^(?P<judgement_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/(?P<mode>input|output|answer|stdout|stderr)\.txt$', views.JudgementTestCaseResultDataView.as_view(), name='judgement_testdata'),
    url(r'^(?P<judgement_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/images/(?P<filename>.*)$', views.JudgementTestCaseResultImageView.as_view(), name='judgement_testimage'),
]

rejudges_urlpatterns = [
    url(r'^new/$', views.CreateRejudgeView.as_view(), name='create_rejudge'),
    url(r'^(?P<rejudge_id>[0-9]+)/$', views.RejudgeView.as_view(), name='rejudge'),
    url(r'^(?P<rejudge_id>[0-9]+)/status/json/$', views.RejudgeJsonView.as_view(), name='rejudge_status_json'),
    url(r'^$', views.RejudgeListView.as_view(), name='rejudge_list'),
]

challenges_urlpatterns = [
    url(r'^$', views.ChallengeListView.as_view(), name='challenge_list'),
]

urlpatterns = [
    url(r'^solutions/', include(solutions_urlpatterns)),
    url(r'^runs/', include(judgements_urlpatterns)),
    url(r'^rejudges/', include(rejudges_urlpatterns)),
    url(r'^challenges/', include(challenges_urlpatterns)),
]

project/problems/templates/problems/delete.html
{% extends 'problems/base.html' %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_messagebox %}

{% block main %}
    {% if error %}
        {% irunner_messagebox style='danger' %}
            <p>{% trans 'Unable to delete the problem because it is currently in use.' %}</p>
        {% irunner_endmessagebox %}
    {% else %}
        <h2>{% trans 'Delete the problem' %}</h2>
        <form method="post">
            {% csrf_token %}
            <p>{% trans 'You should probably do not do this. Consider moving the problem to a special folder instead of permanently deleting it.' %}</p>
            <p>{% trans 'This action cannot be undone.' %}</p>
            {% buttons %}
                <button type="submit" class="btn btn-danger">
                    {% trans 'Delete' %}
                </button>
                <a href="{% url 'problems:name' problem.id %}{{ navigator.query_string }}" class="btn btn-link">
                    {% trans 'Cancel' %}
                </a>
            {% endbuttons %}
        </form>
    {% endif %}
{% endblock %}

project/problems/templates/problems/irunner_problems_difficulty_tag.html
<div class="ir-difficultybox{% if used %} ir-difficultybox-used{% endif %}">{% if difficulty %}{{ difficulty }}{% else %}&nbsp;{% endif %}</div>

project/problems/templates/problems/irunner_problems_io_tag.html
<span class="ir-monospace">{% if emph %}<em>{% endif %}{{ filename }}{% if emph %}</em>{% endif %}</span>

project/problems/templates/problems/irunner_problems_testparams_tag.html
{% load bootstrap3 %}
{% load i18n %}

{% bootstrap_form_errors form %}

<div class="row">
    <div class="col-md-6">
        <table class="ir-test-limits">
            <tbody>
                <tr>
                    <td>{% trans 'Points' %}</td>
                    <td>{% bootstrap_field form.points show_label=False %}</td>
                </tr>
                <tr>
                    <td>{% trans 'Time limit' %}&nbsp;({% trans 's' %})</td>
                    <td>{% bootstrap_field form.time_limit show_label=False show_help=False %}</td>
                </tr>
                <tr>
                    <td>{% trans 'Memory limit' %}&nbsp;({% trans 'MB' %})</td>
                    <td>{% bootstrap_field form.memory_limit show_label=False show_help=False %}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        {% bootstrap_field form.description %}
    </div>
</div>

project/problems/templates/problems/name.html
{% extends 'problems/base.html' %}

{% load bootstrap3 %}
{% load i18n %}

{% block main %}

{% bootstrap_messages %}

<form method="post" class="form-horizontal">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons layout='horizontal' %}
        <button type="submit" class="btn btn-primary">
            {% trans 'Save' %}
        </button>
        <a href="{% url 'problems:delete' problem.id %}{{ navigator.query_string }}" class="btn btn-link">
            {% trans 'Delete the problem' %}
        </button>
    {% endbuttons %}
</form>

{% endblock %}

project/problems/templates/problems/pictures.html
{% extends 'problems/base.html' %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_proglangs %}

{% block main %}
    {% if pictures %}
        <div class="row">
            {% for f in pictures %}
                <div class="col-lg-4 col-sm-6 col-xs-12">
                    <div class="ir-browse-image">
                        <div>{{ f.filename }} <span class="ir-file-size">[{{ f.size|filesizeformat }}]</span></div>
                        <div class="ir-browse-image-data">
                            <a href="#" class="ir-full-image-link">
                                <img src="{% url 'problems:data_file_open' problem.id f.id f.filename %}" class="ir-fit-image" alt="{{ f.filename }}">
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="ir-absence">{% trans 'No pictures' %}</div>
    {% endif %}

    <!-- For showing images -->
    <div class="modal fade" id="ir_image_modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">{% trans 'Image' %}</h4>
                </div>
                <div class="modal-body">
                    <div class="text-center">
                        <img src="" id="ir_image_preview" class="ir-fit-image">
                    </div>
                    <p><a href="#" id="ir_image_raw_link" target="_blank">{% trans 'Open in new tab' %}</a></p>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            $(".ir-full-image-link").click(function(e) {
                e.preventDefault();
                var url = $(this).find("img").attr("src");
                $("#ir_image_preview").attr("src", url);
                $("#ir_image_raw_link").attr("href", url);
                $("#ir_image_modal").modal("show");
            });
        });
    </script>
{% endblock %}

project/problems/templates/problems/show_test.html
{% extends "problems/base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_problems %}
{% load irunner_storage %}
{% load irunner_users %}

{% block main %}

{% bootstrap_messages %}

<nav>
    <ul class="pagination ir-pagination-no-margin">
        <li>
            <a href="{% url 'problems:show_test' problem_id prev_test %}{{ navigator.query_string }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li>
            <a href="{% url 'problems:tests' problem_id %}{{ navigator.query_string }}">
                {% trans 'Test' %} {{ current_test }} {% trans 'of' %} {{ total_tests }}
            </a>
        </li>
        <li>
            <a href="{% url 'problems:show_test' problem_id next_test %}{{ navigator.query_string }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
    <ul class="pagination ir-pagination-no-margin">
        <li>
            <a href="{% url 'problems:edit_test' problem_id current_test %}{{ navigator.query_string }}">
                {% bootstrap_icon 'pencil' %} <span class="ir-icon-label">{% trans 'Edit' %}</span>
            </a>
        </li>
        <li>
            <a href="#" data-toggle="modal" data-target="#myModal">
                {% bootstrap_icon 'trash' %} <span class="ir-icon-label">{% trans 'Delete' %}</span>
            </a>
        </li>
    </ul>
</nav>

<table class="ir-test-info">
    <tbody>
        <tr>
            <td>{% trans 'Points' %}</td>
            <td>{{ points }}</td>
        </tr>
        <tr>
            <td>{% trans 'Time limit' %}</td>
            <td>{% irunner_problems_timelimit time_limit %}</td>
        </tr>
        <tr>
            <td>{% trans 'Memory limit' %}</td>
            <td>{% irunner_problems_memorylimit memory_limit %}</td>
        </tr>
        {% if author != None %}
            <tr>
                <td>{% trans 'Author' %}</td>
                <td>{% irunner_users_show author %}</td>
            </tr>
        {% endif %}
        {% if creation_time != None %}
            <tr>
                <td>{% trans 'Created' context 'test' %}</td>
                <td>{{ creation_time }}</td>
            </tr>
        {% endif %}
        {% if description.text %}
            <tr>
                <td>{% trans 'Description' %}</td>
                <td>{{ description.text|linebreaksbr }}</td>
            </tr>
        {% endif %}
    </tbody>
</table>

{% if description.images %}
    {% if description.images %}
        {% for filename in description.images %}
            <div class="ir-imagebox">
                <div>
                    <div>
                        {% url 'problems:test_image' problem.id current_test filename as img_url %}
                        <a href="{{ img_url }}"><img src="{{ img_url }}" alt="{{ filename }}"></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endif %}

<div class="row">
    <div class="col-md-6">
        <h4>
            <a href="{% url 'problems:test_input_open' problem.id current_test %}" title="{% trans 'Open' %}">{% bootstrap_icon 'open-file' %}</a>
            <a href="{% url 'problems:test_input_download' problem.id current_test %}" title="{% trans 'Download' %}">{% bootstrap_icon 'download-alt' %}</a>
            {% irunner_problems_inputfile problem.input_filename %}
            <span class="ir-file-size">[{{ input_repr.size|filesizeformat }}]</span>
        </h4>
        {% irunner_storage_show input_repr %}
    </div>
    <div class="col-md-6">
        <h4>
            <a href="{% url 'problems:test_answer_open' problem.id current_test %}" title="{% trans 'Open' %}">{% bootstrap_icon 'open-file' %}</a>
            <a href="{% url 'problems:test_answer_download' problem.id current_test %}" title="{% trans 'Download' %}">{% bootstrap_icon 'download-alt' %}</a>
            {% irunner_problems_outputfile problem.output_filename %}
            <span class="ir-file-size">[{{ answer_repr.size|filesizeformat }}]</span>
        </h4>
        {% irunner_storage_show answer_repr %}
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">{% trans 'Confirm' %}</h4>
            </div>
            <div class="modal-body">
                {% trans 'Test case is going to be deleted.' %}
            </div>

            <div class="modal-footer">
                <form method="post" action="{% url 'problems:delete_test' problem.id current_test %}{{ navigator.query_string }}">
                    {% csrf_token %}
                    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Cancel' %}</button>
                    <button type="submit" class="btn btn-danger">{% trans 'Delete' %}</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

project/problems/templates/problems/submission.html
{% extends 'problems/base.html' %}

{% load irunner_solutions %}

{% block main %}
    {% irunner_solutions_livesubmission solution_id %}
{% endblock %}

project/problems/templates/problems/tests_browse.html
{% extends 'problems/base.html' %}

{% load bootstrap3 %}
{% load irunner_storage %}
{% load i18n %}

{% block main %}
{% if not fetched_test_cases %}
    <div class="ir-absence">{% trans 'No tests' %}</div>
{% else %}
<table class="table table-condensed">
    <thead>
        <tr>
            <th>{% trans '#' %}</th>
            <th>{% trans 'Input' %}</th>
            <th>{% trans 'Output' %}</th>
        </tr>
    </thead>
    <tbody>
    {% for ftc in fetched_test_cases %}
        {% with ftc.test_case as tc %}
        <tr>
            <td>
                <a href="{% url 'problems:show_test' problem.id tc.ordinal_number %}{{ navigator.query_string }}">{{ tc.ordinal_number }}</a>
            </td>
            <td>
                <span class="ir-file-size">{{ ftc.test_case.input_size|filesizeformat }}</span>
                {% irunner_storage_show ftc.input_repr compact=True %}
            </td>
            <td>
                <span class="ir-file-size">{{ ftc.test_case.answer_size|filesizeformat }}</span>
                {% irunner_storage_show ftc.answer_repr compact=True %}
            </td>
        </tr>
        {% endwith %}
    {% endfor %}
    </tbody>
</table>
{% endif %}
{% endblock %}

project/problems/templates/problems/texs.html
{% extends 'problems/base.html' %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_proglangs %}

{% block main %}
    <table class="table table-condensed table-hover table-bordered ir-problem-files-table">
        <thead>
            <tr>
                <th class="ir-col-filename">{% trans 'File' %}</th>
                <th class="ir-col-filetype">{% trans 'Type' %}</th>
            </tr>
        </thead>
        <tbody>
        {% for f in related_files %}
            <tr>
                <td class="ir-col-filename">
                    <a href="{% url 'problems:edit_tex' problem.id f.id %}{{ navigator.query_string }}">{{ f.filename }}</a> <span class="ir-file-size">[{{ f.size|filesizeformat }}]</span>
                </td>
                <td class="ir-col-filetype">{{ f.get_file_type_display }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% buttons %}
        <a href="{% url 'problems:tex_new_statement' problem.id %}{{ navigator.query_string }}" class="btn btn-default">{% bootstrap_icon 'plus' %} <span class="ir-icon-label">{% trans 'New statement' %}</span></a>
        <a href="#" class="btn btn-default disabled">{% bootstrap_icon 'plus' %} <span class="ir-icon-label">{% trans 'New editorial' %}</span></a>
    {% endbuttons %}
{% endblock %}