project/api/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^fs/status$', views.FileStatusView.as_view(), name='fs_status'),
    url(r'^fs/(?P<filename>[0-9a-f]*)$', views.FileView.as_view(), name='fs_status'),
    url(r'^jobs/take$', views.JobTakeView.as_view(), name='take_job'),
    url(r'^jobs/(?P<job_id>\d+)/result$', views.JobPutResultView.as_view()),
    url(r'^jobs/(?P<job_id>\d+)/state$', views.JobPutStateView.as_view()),
    url(r'^compiler-settings$', views.CompilerSettingsView.as_view()),
    url(r'^plagiarism/take$', views.PlagiarismTakeView.as_view()),
    url(r'^plagiarism/put$', views.PlagiarismPutView.as_view()),
    url(r'^sleep$', views.SleepView.as_view()),
    url(r'^printing$', views.PrintingView.as_view()),
    url(r'^printing/(?P<printout_id>\d+)$', views.PrintingDoneView.as_view()),

    url(r'^queue/$', views.QueueView.as_view(), name='queue')
]

project/courses/urls.py
from django.conf.urls import url

from . import views, globalviews, settingsviews, assignviews

urlpatterns = [
    url(r'^$', globalviews.CourseListView.as_view(), name='index'),
    url(r'^new/$', globalviews.CourseCreateView.as_view(), name='new'),

    url(r'^criteria/$', views.CriterionListView.as_view(), name='criterion_index'),
    url(r'^criteria/new/$', views.CriterionCreateView.as_view(), name='criterion_new'),
    url(r'^criteria/(?P<pk>[0-9]+)/edit/$', views.CriterionUpdateView.as_view(), name='criterion_edit'),
    url(r'^criteria/(?P<pk>[0-9]+)/delete/$', views.CriterionDeleteView.as_view(), name='criterion_delete'),

    url(r'^(?P<course_id>[0-9]+)/$', views.CourseInfoView.as_view(), name='show_course_info'),
    url(r'^(?P<course_id>[0-9]+)/standings/$', views.CourseStandingsView.as_view(), name='course_standings'),
    url(r'^(?P<course_id>[0-9]+)/standings/wide/$', views.CourseStandingsWideView.as_view(), name='course_standings_wide'),
    url(r'^(?P<course_id>[0-9]+)/sheet/$', views.CourseSheetView.as_view(), name='course_sheet'),
    url(r'^(?P<course_id>[0-9]+)/sheet/edit/$', views.CourseSheetEditView.as_view(), name='course_sheet_edit'),
    url(r'^(?P<course_id>[0-9]+)/sheet/edit/api/(?P<membership_id>[0-9]+)/(?P<activity_id>[0-9]+)/$', views.CourseSheetEditApiView.as_view(), name='course_sheet_edit_api'),
    url(r'^(?P<course_id>[0-9]+)/compilers/$', views.CourseCompilersView.as_view(), name='course_compilers'),

    url(r'^(?P<course_id>[0-9]+)/submit/$', views.CourseSubmitView.as_view(), name='course_submit'),
    url(r'^(?P<course_id>[0-9]+)/submission/(?P<solution_id>[0-9]+)/$', views.CourseSubmissionView.as_view(), name='course_submission'),

    url(r'^(?P<course_id>[0-9]+)/problemset/$', views.CourseProblemsView.as_view(), name='course_problems'),
    url(r'^(?P<course_id>[0-9]+)/problemset/(?P<topic_id>[0-9]+)/$', views.CourseProblemsTopicView.as_view(), name='course_problems_topic'),
    url(r'^(?P<course_id>[0-9]+)/problemset/(?P<topic_id>[0-9]+)/(?P<problem_id>[0-9]+)/(?P<filename>.+)?$', views.CourseProblemsTopicProblemView.as_view(), name='course_problems_topic_problem'),
    url(r'^(?P<course_id>[0-9]+)/problems/(?P<problem_id>[0-9]+)/(?P<filename>.+)?$', views.CourseProblemsProblemView.as_view(), name='course_problems_problem'),

    url(r'^(?P<course_id>[0-9]+)/solutions/$', views.CourseAllSolutionsView.as_view(), name='all_solutions'),
    url(r'^(?P<course_id>[0-9]+)/my/solutions/$', views.CourseMySolutionsView.as_view(), name='my_solutions'),

    url(r'^(?P<course_id>[0-9]+)/my/problems/$', views.CourseMyProblemsView.as_view(), name='my_problems'),

    url(r'^(?P<course_id>[0-9]+)/my/attempts/$', views.CourseMyAttemptsView.as_view(), name='my_attempts'),

    # Messages

    url(r'^(?P<course_id>[0-9]+)/mailbox/$', views.CourseMessagesEmptyView.as_view(), name='messages_empty'),
    url(r'^(?P<course_id>[0-9]+)/mailbox/(?P<thread_id>[0-9]+)/$', views.CourseMessagesView.as_view(), name='messages'),
    url(r'^(?P<course_id>[0-9]+)/mailbox/(?P<thread_id>[0-9]+)/delete/$', views.CourseMessagesThreadDeleteView.as_view(), name='messages_thread_delete'),
    url(r'^(?P<course_id>[0-9]+)/mailbox/(?P<thread_id>[0-9]+)/resolve/$', views.CourseMessagesThreadResolveView.as_view(), name='messages_thread_resolve'),
    url(r'^(?P<course_id>[0-9]+)/mailbox/(?P<thread_id>[0-9]+)/messages/(?P<message_id>[0-9]+)/attachment/(?P<filename>.*)$', views.CourseMessagesDownloadView.as_view(), name='messages_download'),
    url(r'^(?P<course_id>[0-9]+)/mailbox/new/$', views.CourseMessagesNewView.as_view(), name='messages_new'),

    # Problem assignment

    url(r'^(?P<course_id>[0-9]+)/assign/$', assignviews.CourseEmptyAssignView.as_view(), name='course_assignment_empty'),
    url(r'^(?P<course_id>[0-9]+)/assign/(?P<user_id>[0-9]+)/$', assignviews.CourseAssignView.as_view(), name='course_assignment'),
    url(r'^(?P<course_id>[0-9]+)/assign/(?P<user_id>[0-9]+)/new-penalty/$', assignviews.CourseAssignCreatePenaltyProblem.as_view(), name='course_assignment_new_penalty'),
    url(r'^(?P<course_id>[0-9]+)/assign/(?P<user_id>[0-9]+)/delete-penalty/(?P<assignment_id>[0-9]+)/$', assignviews.CourseAssignDeletePenaltyProblem.as_view(), name='course_assignment_delete_penalty'),
    url(r'^(?P<course_id>[0-9]+)/assign/(?P<user_id>[0-9]+)/api/problem/$', assignviews.CourseAssignProblemApiView.as_view(), name='course_assignment_api_problem'),
    url(r'^(?P<course_id>[0-9]+)/assign/(?P<user_id>[0-9]+)/api/criterion/$', assignviews.CourseAssignCriterionApiView.as_view(), name='course_assignment_api_criterion'),
    url(r'^(?P<course_id>[0-9]+)/assign/(?P<user_id>[0-9]+)/api/topic-problems/(?P<topic_id>[0-9]+)/$', assignviews.ListTopicProblemsApiView.as_view()),

    # Settings

    url(r'^(?P<course_id>[0-9]+)/settings/$', settingsviews.CourseSettingsPropertiesView.as_view(), name='course_settings_properties'),

    url(r'^(?P<course_id>[0-9]+)/settings/delete/$', settingsviews.CourseSettingsDeleteView.as_view(), name='course_settings_delete'),

    url(r'^(?P<course_id>[0-9]+)/settings/access/$', settingsviews.CourseSettingsAccessView.as_view(), name='course_settings_access'),

    url(r'^(?P<course_id>[0-9]+)/settings/problems/$', settingsviews.CourseSettingsProblemsView.as_view(), name='course_settings_problems'),
    url(r'^(?P<course_id>[0-9]+)/settings/problems/topics/create/$', settingsviews.CourseSettingsTopicsCreateView.as_view(), name='course_settings_topics_create'),
    url(r'^(?P<course_id>[0-9]+)/settings/problems/topics/(?P<pk>[0-9]+)/$', settingsviews.CourseSettingsTopicsUpdateView.as_view(), name='course_settings_topics_update'),
    url(r'^(?P<course_id>[0-9]+)/settings/problems/common/$', settingsviews.CourseSettingsCommonProblemsView.as_view(), name='course_settings_common_problems'),
    url(r'^(?P<course_id>[0-9]+)/settings/problems/list/(?P<folder_id>[0-9]+)/$', settingsviews.CourseSettingsProblemsJsonListView.as_view(), name='course_settings_problems_json_list'),

    url(r'^(?P<course_id>[0-9]+)/settings/sheet/$', settingsviews.CourseSettingsSheetActivityListView.as_view(), name='course_settings_sheet'),
    url(r'^(?P<course_id>[0-9]+)/settings/sheet/activities/create/$', settingsviews.CourseSettingsSheetActivityCreateView.as_view(), name='course_settings_sheet_activity_create'),
    url(r'^(?P<course_id>[0-9]+)/settings/sheet/activities/(?P<pk>[0-9]+)/$', settingsviews.CourseSettingsSheetActivityUpdateView.as_view(), name='course_settings_sheet_activity_update'),

    url(r'^(?P<course_id>[0-9]+)/settings/subgroups/$', settingsviews.CourseSettingsSubgroupListView.as_view(), name='course_settings_subgroups'),
    url(r'^(?P<course_id>[0-9]+)/settings/subgroups/new/$', settingsviews.CourseSettingsSubgroupCreateView.as_view(), name='course_settings_subgroup_create'),
    url(r'^(?P<course_id>[0-9]+)/settings/subgroups/(?P<pk>[0-9]+)/$', settingsviews.CourseSettingsSubgroupUpdateView.as_view(), name='course_settings_subgroup_update'),

    url(r'^(?P<course_id>[0-9]+)/settings/users/$', settingsviews.CourseSettingsUsersView.as_view(), name='course_settings_users'),
    url(r'^(?P<course_id>[0-9]+)/settings/users/students/$', settingsviews.CourseSettingsUsersStudentsView.as_view(), name='course_settings_users_students'),
    url(r'^(?P<course_id>[0-9]+)/settings/users/teachers/$', settingsviews.CourseSettingsUsersTeachersView.as_view(), name='course_settings_users_teachers'),
    url(r'^(?P<course_id>[0-9]+)/settings/users/list/(?P<folder_id>[0-9]+)/$', settingsviews.CourseSettingsUsersJsonListView.as_view(), name='course_settings_users_json_list'),

    url(r'^(?P<course_id>[0-9]+)/settings/compilers/$', settingsviews.CourseSettingsCompilersView.as_view(), name='course_settings_compilers'),
    url(r'^(?P<course_id>[0-9]+)/settings/subgroups/$', settingsviews.CourseSettingsSubgroupsView.as_view(), name='course_settings_subgroups'),
]

project/irunner2/urls.py
from django.conf.urls import include, url
#from django.contrib import admin
import common.views
from django_js_reverse.views import urls_js
from django.views.decorators.cache import cache_page


urlpatterns = [
    url(r'^$', common.views.home, name='home'),
    url(r'^language/$', common.views.language, name='language'),
    url(r'^feedback/', include('feedback.urls', namespace='feedback')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^i18n/', include('django.conf.urls.i18n'), name='set_language'),
    url(r'^storage/', include('storage.urls', namespace='storage')),
    url(r'^problems/', include('problems.urls', namespace='problems')),
    url(r'^compilers/', include('proglangs.urls', namespace='proglangs')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^', include('solutions.urls', namespace='solutions')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^contests/', include('contests.urls', namespace='contests')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^quiz-demo/', include('quizdemo.urls', namespace='quizdemo')),
    url(r'^about/', common.views.about, name='about'),
    url('^', include('cauth.urls')),
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^jsreverse/$', cache_page(3600)(urls_js), name='js_reverse'),
    url(r'^hall-of-fame/$', common.views.HallOfFameView.as_view(), name='hall_of_fame'),
    url(r'^activity/$', common.views.ActivityView.as_view(), name='activity'),
]

handler403 = 'common.views.error403'

project/solutions/urls.py
from django.conf.urls import include, url

from . import views

solutions_urlpatterns = [
    url(r'^$', views.SolutionListView.as_view(), name='list'),

    url(r'^(?P<solution_id>[0-9]+)/$', views.SolutionMainView.as_view(), name='main'),
    url(r'^(?P<solution_id>[0-9]+)/source/$', views.SolutionSourceView.as_view(), name='source'),
    url(r'^(?P<solution_id>[0-9]+)/log/$', views.SolutionLogView.as_view(), name='log'),
    url(r'^(?P<solution_id>[0-9]+)/tests/$', views.SolutionTestsView.as_view(), name='tests'),
    url(r'^(?P<solution_id>[0-9]+)/runs/$', views.SolutionJudgementsView.as_view(), name='judgements'),
    url(r'^(?P<solution_id>[0-9]+)/attempts/$', views.SolutionAttemptsView.as_view(), name='attempts'),
    url(r'^(?P<solution_id>[0-9]+)/plagiarism/$', views.SolutionPlagiarismView.as_view(), name='plagiarism'),
    url(r'^(?P<solution_id>[0-9]+)/status/json/$', views.SolutionStatusJsonView.as_view(), name='status_json'),

    url(r'^(?P<solution_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/$', views.SolutionTestCaseResultView.as_view(), name='test_case_result'),
    url(r'^(?P<solution_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/(?P<mode>input|output|answer|stdout|stderr)\.txt$', views.SolutionTestCaseResultDataView.as_view(), name='test_data'),
    url(r'^(?P<solution_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/images/(?P<filename>.*)$', views.SolutionTestCaseResultImageView.as_view(), name='test_image'),

    url(r'^(?P<solution_id>[0-9]+)/source/open/(?P<filename>.*)$', views.SolutionSourceOpenView.as_view(), name='source_open'),
    url(r'^(?P<solution_id>[0-9]+)/source/download/(?P<filename>.*)$', views.SolutionSourceDownloadView.as_view(), name='source_download'),

    url(r'^delete/$', views.DeleteSolutionsView.as_view(), name='delete'),

    url(r'^compare/$', views.CompareSolutionsView.as_view(), name='compare'),
]

judgements_urlpatterns = [
    url(r'^$', views.JudgementListView.as_view(), name='judgement_list'),
    url(r'^(?P<judgement_id>[0-9]+)/$', views.JudgementView.as_view(), name='show_judgement'),
    url(r'^(?P<judgement_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/$', views.JudgementTestCaseResultView.as_view(), name='judgement_testcaseresult'),
    url(r'^(?P<judgement_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/(?P<mode>input|output|answer|stdout|stderr)\.txt$', views.JudgementTestCaseResultDataView.as_view(), name='judgement_testdata'),
    url(r'^(?P<judgement_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/images/(?P<filename>.*)$', views.JudgementTestCaseResultImageView.as_view(), name='judgement_testimage'),
]

rejudges_urlpatterns = [
    url(r'^new/$', views.CreateRejudgeView.as_view(), name='create_rejudge'),
    url(r'^(?P<rejudge_id>[0-9]+)/$', views.RejudgeView.as_view(), name='rejudge'),
    url(r'^(?P<rejudge_id>[0-9]+)/status/json/$', views.RejudgeJsonView.as_view(), name='rejudge_status_json'),
    url(r'^$', views.RejudgeListView.as_view(), name='rejudge_list'),
]

challenges_urlpatterns = [
    url(r'^$', views.ChallengeListView.as_view(), name='challenge_list'),
]

urlpatterns = [
    url(r'^solutions/', include(solutions_urlpatterns)),
    url(r'^runs/', include(judgements_urlpatterns)),
    url(r'^rejudges/', include(rejudges_urlpatterns)),
    url(r'^challenges/', include(challenges_urlpatterns)),
]

project/courses/templates/courses/info.html
{% extends 'courses/base.html' %}

{% load bootstrap3 %}
{% load i18n %}
{% load staticfiles %}
{% load irunner_courses %}
{% load irunner_problems %}
{% load irunner_stats %}

{% block title %}{{ course }}{% endblock %}

{% block head %}
    <script src="{% static 'flot-0.8.3/jquery.flot.min.js' %}"></script>
    <script src="{% static 'flot-0.8.3/jquery.flot.time.min.js' %}"></script>
    <script src="{% static 'flot-0.8.3/jquery.flot.resize.min.js' %}"></script>
    <!--[if lte IE 8]><script language="javascript" type="text/javascript" src="{% static 'flot-0.8.3/excanvas.min.js' %}"></script><![endif]-->
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-lg-7">
            <div class="panel panel-default">
                <div class="panel-heading">{% trans 'Number of submitted solutions' %}</div>
                <div class="panel-body">
                    {% if show_activity_plot %}
                        <div class="ir-activity-plot"></div>
                    {% else %}
                        <div class="ir-absence">{% trans 'No solutions' %}</div>
                    {% endif %}
                </div>
            </div>

            {% if language_bars %}
                <div class="panel panel-default">
                    <div class="panel-heading">{% trans 'Programming language popularity' %}</div>
                    <div class="panel-body">
                        {% irunner_stats_proglangbars language_bars %}
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="col-lg-5">
            <div class="panel panel-default">
                <div class="panel-heading">{% trans 'Latest accepted solutions' %}</div>
                <div class="panel-body">
                    {% if latest_accepted_solutions %}
                        {% for solution in latest_accepted_solutions %}
                            <div class="ir-latest-solver">
                                {% bootstrap_icon 'time' %} <span class="ir-icon-label">{{ solution.reception_time|timesince }} {% trans 'ago' %}</span>
                                <br>
                                {% bootstrap_icon 'user' %} <span class="ir-icon-label">{% if permissions.assign %}{% url 'courses:course_assignment' course.id solution.author_id as assign_url %}{% irunner_courses_user_card solution.author_id user_cache url=assign_url %}{% else %}{% irunner_courses_user_card solution.author_id user_cache %}{% endif %}</span>
                                <br>
                                {% bootstrap_icon 'file' %}
                                {% irunner_problems_difficulty solution.problem.difficulty %}
                                <a href="{% url 'courses:course_problems_problem' course.id solution.problem_id %}">{{ solution.problem.numbered_full_name }}</a>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="ir-absence">{% trans 'No solutions' %}</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            var allSolutionSeries = {
                color: "#337ab7",
                label: "{% trans 'all' %}",
                data: {{ all_solution_json|safe }}
            };
            var acceptedSolutionSeries = {
                color: "#5cb85c",
                label: "{% trans 'accepted' %}",
                data: {{ accepted_solution_json|safe }}
            };

            var data = [allSolutionSeries, acceptedSolutionSeries];
            var options = {
                series: {
                    lines: { show: true },
                    points: { show: true, radius: 1, fill: true }
                },
                xaxis: {
                    mode: "time",
                    timeformat: "%d %b"
                },
                yaxis: {
                    tickDecimals: 0,
                    min: 0,
                },
                legend: { position: "nw" }
            };
            var div = $(".ir-activity-plot").first();
            if (div.length) {
                $.plot(div, data, options);
            }
        });
    </script>
{% endblock %}

project/courses/templates/courses/irunner_courses_slotresult_tag.html
{% load bootstrap3 %}
{% load i18n %}
{% load irunner_courses %}
{% load irunner_problems %}
{% load irunner_proglangs %}
{% load irunner_solutions %}

{# variables in context: slot_result, problem_result #}

<div
    class="ir-slot-result"
    {% if slot_result %}
        {% if slot_result.slot %} data-slot="{{ slot_result.slot.id }}"{% endif %}
        {% if slot_result.assignment %} data-assignment="{{ slot_result.assignment.id }}"{% endif %}
        data-topic="{{ slot_result.topic_descr.topic.id }}"
    {% endif %}
>
    <div class="row">
        <div class="col-sm-9">
            <div>
                {% if problem_result %}
                    {% irunner_problems_difficulty problem_result.problem.difficulty %}
                    <a href="{% url 'courses:course_problems_problem' course_id problem_result.problem.id %}" title="{% trans 'Statement' %}">{{ problem_result.problem.numbered_full_name }}</a>
                {% else %}
                    <span class="ir-absence">{% trans 'No problem is assigned' %}</span>
                {% endif %}
                {% if editable %}
                    <button type="button" class="btn btn-xs btn-default ir-assign-button" title="{% trans 'Assign' %}">{% bootstrap_icon 'pencil' %}</button>
                {% endif %}
            </div>
            {% if problem_result %}
                {% if problem_result.best_solution %}
                    <div class="ir-best-solution">
                        {% url 'solutions:main' problem_result.best_solution.id as s_url %}
                        {% url 'solutions:source' problem_result.best_solution.id as c_url %}
                        <a href="{{ s_url }}">{% irunner_solutions_judgementbox problem_result.best_solution.best_judgement tooltip=True %}</a>
                        <a href="{{ s_url }}">{% irunner_solutions_scorebox problem_result.best_solution.best_judgement %}</a>
                        <a href="{{ c_url }}">{% irunner_proglangs_compilerbox problem_result.best_solution.compiler tooltip=True %}</a>
                    </div>
                {% endif %}
            {% endif %}
        </div>
        <div class="col-sm-3">
            {% if slot_result %}
                {% for criterion_descr in slot_result.criterion_descrs %}
                    <div {% if editable %} class="ir-toggle-criterion"{% endif %}>
                        {% irunner_courses_criterion criterion_descr.criterion criterion_descr.ok editable=editable %}
                        {{ criterion_descr.criterion.name }}
                    </div>
                {% endfor %}
            {% endif %}
            {% if problem_result %}
            <div>
                <div class="ir-box ir-criterion ir-criterion-{{ problem_result.is_ok|yesno:"yes,no" }}"><span class="invisible">&nbsp;</span></div>
                {% if problem_result.solutions %}
                    {% with problem_result.solutions|length as cnt %}
                        <a href="{% if user_id %}{% url 'courses:all_solutions' course_id %}?user={{ user_id }}&amp;problem={{ problem_result.problem.id }}{% else %}{% url 'courses:my_solutions' course_id %}?problem={{ problem_result.problem.id }}{% endif %}">{{ cnt }}&nbsp;{% blocktrans count counter=cnt %}solution{% plural %}solutions{% endblocktrans %}</a>
                    {% endwith %}
                {% else %}
                    {% trans 'No solutions' %}
                {% endif %}
            </div>
            {% endif %}
        </div>
    </div>
</div>

project/courses/templates/courses/problems_base.html
{% extends 'courses/base.html' %}

{% load i18n %}

{% block subtitle %}{% trans 'Course problems' %}{% endblock %}

{% block main %}
<div>
    {% if navigate_topics %}
    <div class="ir-float-parent">
        <ul class="nav nav-pills ir-inline-block ir-condensed-pills">
            {% for topic in topics %}
            <li role="presentation"{% if active_topic == topic %} class="active"{% endif %}>
                <a href="{% url 'courses:course_problems_topic' course.id topic.id %}">{{ topic.name }}</a>
            </li>
            {% endfor %}
        </ul>

        {% if prev_next %}
        <ul class="pagination navbar-right ir-pagination-no-margin">
            <li>
                <a href="{% url 'courses:course_problems_topic_problem' course.id active_topic.id prev_problem_id %}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <li>
                <a href="{% url 'courses:course_problems_topic' course.id active_topic.id %}">
                    {{ cur_position }} {% trans 'of' %} {{ total_positions }}
                </a>
            </li>
            <li>
                <a href="{% url 'courses:course_problems_topic_problem' course.id active_topic.id next_problem_id %}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
        {% endif %}
    </div>

    <div class="ir-pill-content">
    {% endif %}
        {% block submain %}
            {% trans 'Select a topic to view problems.' %}
        {% endblock %}
    {% if navigate_topics %}
    </div>
    {% endif %}
</div>
{% endblock %}

project/courses/templates/courses/settings_problems.html
{% extends 'courses/settings_base.html' %}

{% load i18n %}
{% load irunner_courses %}
{% load irunner_problems %}

{% block submain %}
    <h3>{% trans 'Topics' %}</h3>
    {% if object_list %}
        <ul>
        {% for topic in object_list %}
            <li>
                <a href="{% url 'courses:course_settings_topics_update' course.id topic.id %}">{{ topic.name }}</a>
                <dl class="dl-horizontal">
                    <dt>{% trans 'Folder' %}</dt>
                    <dd>
                        {% if topic.problem_folder %}
                            &laquo;{{ topic.problem_folder }}&raquo;
                            ({% blocktrans count counter=topic.problem_folder.problem_set.count %}{{ counter }} problem{% plural %}{{ counter }} problems{% endblocktrans %})
                        {% else %}
                            &mdash;
                        {% endif %}
                    </dd>

                    <dt>{% trans 'To assign' %}</dt>
                    <dd>{% blocktrans count counter=topic.slot_set.count %}{{ counter }} problem{% plural %}{{ counter }} problems{% endblocktrans %}</dd>

                    <dt>{% trans 'Criteria' %}</dt>
                    <dd>
                        {% for criterion in topic.criteria.all %}
                            {% irunner_courses_criterion criterion True tooltip=True %}
                        {% endfor %}
                    </dd>
                </dl>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        {% trans 'No topics' %}
    {% endif %}
    <p>
        <a href="{% url 'courses:course_settings_topics_create' course.id %}">{% trans 'New topic' %}</a>
    </p>

    <h3>{% trans 'Common problems' %}</h3>
    <p class="help-block">
        {% trans 'These problems are not assigned individually. Every student can solve them.' %}
    </p>

    <ul>
        {% for problem in common_problems %}
            <li>
                {% irunner_problems_difficulty problem.difficulty %}
                <a href="{% url 'courses:course_problems_problem' course.id problem.id %}">{{ problem.numbered_full_name }}</a>
            </li>
        {% endfor %}
    </ul>

    <p><a href="{% url 'courses:course_settings_common_problems' course.id %}">{% trans 'Edit the list' %}</a></p>
{% endblock %}

project/courses/templates/courses/settings_sheet.html
{% extends 'courses/settings_base.html' %}

{% load i18n %}

{% block submain %}

{% if sum_is_bad %}
    <div class="alert alert-warning" role="alert">
        {% blocktrans %}<strong>Warning!</strong> Sum of weights is {{ sum_actual }}, but {{ sum_expected }} is required.{% endblocktrans %}
    </div>
{% endif %}

{% if main_activities %}
    <h3>{% trans 'Main kinds of activity' %}</h3>
    <ul>
    {% for activity in main_activities %}
        <li>
            <a href="{% url 'courses:course_settings_sheet_activity_update' course.id activity.id %}">{{ activity.name }}</a>&nbsp;&mdash; {% trans 'weight' %} <strong>{{ activity.weight }}</strong>: {{ activity.get_kind_display }}
        </li>
    {% endfor %}
    </ul>
{% endif %}

{% if extra_activities %}
    <h3>{% trans 'Extra kinds of activity' %}</h3>
    <ul>
    {% for activity in extra_activities %}
        <li>
            <a href="{% url 'courses:course_settings_sheet_activity_update' course.id activity.id %}">{{ activity.name }}</a>&nbsp;&mdash; {{ activity.get_kind_display }}
        </li>
    {% endfor %}
    </ul>
{% endif %}

<p>
    <a href="{% url 'courses:course_settings_sheet_activity_create' course.id %}">{% trans 'New kind of activity' %}</a>
</p>
{% endblock %}