project/api/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^fs/status$', views.FileStatusView.as_view(), name='fs_status'),
    url(r'^fs/(?P<filename>[0-9a-f]*)$', views.FileView.as_view(), name='fs_status'),
    url(r'^jobs/take$', views.JobTakeView.as_view(), name='take_job'),
    url(r'^jobs/(?P<job_id>\d+)/result$', views.JobPutResultView.as_view()),
    url(r'^jobs/(?P<job_id>\d+)/state$', views.JobPutStateView.as_view()),
    url(r'^compiler-settings$', views.CompilerSettingsView.as_view()),
    url(r'^plagiarism/take$', views.PlagiarismTakeView.as_view()),
    url(r'^plagiarism/put$', views.PlagiarismPutView.as_view()),
    url(r'^sleep$', views.SleepView.as_view()),
    url(r'^printing$', views.PrintingView.as_view()),
    url(r'^printing/(?P<printout_id>\d+)$', views.PrintingDoneView.as_view()),

    url(r'^queue/$', views.QueueView.as_view(), name='queue')
]

project/irunner2/urls.py
from django.conf.urls import include, url
#from django.contrib import admin
import common.views
from django_js_reverse.views import urls_js
from django.views.decorators.cache import cache_page


urlpatterns = [
    url(r'^$', common.views.home, name='home'),
    url(r'^language/$', common.views.language, name='language'),
    url(r'^feedback/', include('feedback.urls', namespace='feedback')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^i18n/', include('django.conf.urls.i18n'), name='set_language'),
    url(r'^storage/', include('storage.urls', namespace='storage')),
    url(r'^problems/', include('problems.urls', namespace='problems')),
    url(r'^compilers/', include('proglangs.urls', namespace='proglangs')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^', include('solutions.urls', namespace='solutions')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^contests/', include('contests.urls', namespace='contests')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^quiz-demo/', include('quizdemo.urls', namespace='quizdemo')),
    url(r'^about/', common.views.about, name='about'),
    url('^', include('cauth.urls')),
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^jsreverse/$', cache_page(3600)(urls_js), name='js_reverse'),
    url(r'^hall-of-fame/$', common.views.HallOfFameView.as_view(), name='hall_of_fame'),
    url(r'^activity/$', common.views.ActivityView.as_view(), name='activity'),
]

handler403 = 'common.views.error403'

project/problems/urls.py
from django.conf.urls import include, url

from . import views

problem_urlpatterns = [
    url(r'^$', views.ProblemOverviewView.as_view(), name='overview'),
    url(r'^statement/(?P<filename>.+)?$', views.ProblemStatementView.as_view(), name='statement'),

    url(r'^tests/$', views.ProblemTestsView.as_view(), name='tests'),
    url(r'^tests/browse/$', views.ProblemBrowseTestsView.as_view(), name='browse_tests'),
    url(r'^tests/(?P<test_number>[0-9]+)/$', views.ProblemTestsTestView.as_view(), name='show_test'),
    url(r'^tests/upload/$', views.ProblemTestsUploadArchiveView.as_view(), name='upload_archive'),
    url(r'^tests/new/$', views.ProblemTestsNewView.as_view(), name='new_test'),
    url(r'^tests/(?P<test_number>[0-9]+)/edit/$', views.ProblemTestsTestEditView.as_view(), name='edit_test'),
    url(r'^tests/(?P<test_number>[0-9]+)/delete/$', views.ProblemTestsDeleteView.as_view(), name='delete_test'),
    url(r'^tests/(?P<test_number>[0-9]+)/image/(?P<filename>.+)$', views.ProblemTestsTestImageView.as_view(), name='test_image'),
    url(r'^tests/batch/set/time-limit/$', views.ProblemTestsSetTimeLimitView.as_view(), name='tests_mass_time_limit'),
    url(r'^tests/batch/set/memory-limit/$', views.ProblemTestsSetMemoryLimitView.as_view(), name='tests_mass_memory_limit'),
    url(r'^tests/batch/set/points/$', views.ProblemTestsSetPointsView.as_view(), name='tests_mass_points'),
    url(r'^tests/batch/delete/$', views.ProblemTestsBatchDeleteView.as_view(), name='tests_mass_delete'),

    url(r'^tests/open/input-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='input', download=False), name='test_input_open'),
    url(r'^tests/download/input-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='input', download=True), name='test_input_download'),
    url(r'^tests/open/answer-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='answer', download=False), name='test_answer_open'),
    url(r'^tests/download/answer-(?P<test_number>[0-9]+)\.txt$', views.ProblemTestsTestDataView.as_view(kind='answer', download=True), name='test_answer_download'),

    url(r'^solutions/$', views.ProblemSolutionsView.as_view(), name='solutions'),
    url(r'^solutions/process/$', views.ProblemSolutionsProcessView.as_view(), name='solutions_process'),

    url(r'^files/$', views.ProblemFilesView.as_view(), name='files'),
    url(r'^files/data/(?P<file_id>[0-9]+)/open/(?P<filename>.+)$', views.ProblemFilesFileOpenView.as_view(), name='data_file_open'),
    url(r'^files/data/(?P<file_id>[0-9]+)/download/(?P<filename>.+)$', views.ProblemFilesFileOpenView.as_view(download=True), name='data_file_download'),
    url(r'^files/data/(?P<file_id>[0-9]+)/edit/$', views.ProblemFilesDataFileEditView.as_view(), name='data_file_edit'),
    url(r'^files/data/(?P<file_id>[0-9]+)/delete/$', views.ProblemFilesDataFileDeleteView.as_view(), name='data_file_delete'),
    url(r'^files/data/new/$', views.ProblemFilesDataFileNewView.as_view(), name='data_file_new'),

    url(r'^files/source/(?P<file_id>[0-9]+)/open/(?P<filename>.+)$', views.ProblemFilesSourceFileOpenView.as_view(), name='source_file_open'),
    url(r'^files/source/(?P<file_id>[0-9]+)/download/(?P<filename>.+)$', views.ProblemFilesSourceFileOpenView.as_view(download=True), name='source_file_download'),
    url(r'^files/source/(?P<file_id>[0-9]+)/edit/$', views.ProblemFilesSourceFileEditView.as_view(), name='source_file_edit'),
    url(r'^files/source/(?P<file_id>[0-9]+)/delete/$', views.ProblemFilesSourceFileDeleteView.as_view(), name='source_file_delete'),
    url(r'^files/source/new/$', views.ProblemFilesSourceFileNewView.as_view(), name='source_file_new'),

    url(r'^tex/$', views.ProblemTeXView.as_view(), name='tex'),
    url(r'^tex/render/$', views.ProblemTeXRenderView.as_view(), name='tex_render'),
    url(r'^tex/new/statement/$', views.ProblemTeXNewStatementView.as_view(), name='tex_new_statement'),
    url(r'^tex/(?P<file_id>[0-9]+)/$', views.ProblemTeXEditView.as_view(), name='edit_tex'),
    url(r'^tex/(?P<file_id>[0-9]+)/(?P<filename>.+)$', views.ProblemTeXEditRelatedFileView.as_view()),

    url(r'^challenges/$', views.ProblemChallengesView.as_view(), name='challenges'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/$', views.ProblemChallengeView.as_view(), name='challenge'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/add-test/$', views.ProblemChallengeAddTestView.as_view(), name='challenge_add_test'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/status/json/$', views.ProblemChallengeJsonView.as_view(), name='challenge_status_json'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/open/(?P<resource_id>[0-9a-f]*)/(?P<filename>[a-z0-9\-]+)\.txt$', views.ProblemChallengeDataView.as_view(download=False), name='challenge_data_open'),
    url(r'^challenges/(?P<challenge_id>[0-9]+)/download/(?P<resource_id>[0-9a-f]*)/(?P<filename>[a-z0-9\-]+)\.txt$', views.ProblemChallengeDataView.as_view(download=True), name='challenge_data_download'),
    url(r'^challenges/new/$', views.ProblemNewChallengeView.as_view(), name='new_challenge'),

    url(r'^rejudges/$', views.ProblemRejudgesView.as_view(), name='rejudges'),

    url(r'^submit/$', views.ProblemSubmitView.as_view(), name='submit'),
    url(r'^submission/(?P<solution_id>[0-9]+)/$', views.ProblemSubmissionView.as_view(), name='submission'),
    url(r'^folders/$', views.ProblemFoldersView.as_view(), name='folders'),
    url(r'^name/$', views.ProblemNameView.as_view(), name='name'),
    url(r'^properties/$', views.ProblemPropertiesView.as_view(), name='properties'),
    url(r'^pictures/$', views.ProblemPicturesView.as_view(), name='pictures'),
    url(r'^validator/$', views.ProblemValidatorView.as_view(), name='validator'),
    url(r'^delete/$', views.ProblemDeleteView.as_view(), name='delete'),
]

urlpatterns = [
    url(r'^tree/$', views.ShowTreeView.as_view(), name='show_tree'),
    url(r'^tree/(?P<folder_id>[0-9]+)/$', views.ShowTreeFolderView.as_view(), name='show_tree_folder'),
    url(r'^tree/(?P<folder_id>[0-9]+)/json/$', views.ShowTreeFolderJsonView.as_view(), name='show_tree_folder_json'),

    url(r'^(?P<problem_id>[0-9]+)/', include(problem_urlpatterns)),

    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/$', views.ShowFolderView.as_view(), name='show_folder'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/new/folder/$', views.CreateFolderView.as_view(), name='create_folder'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/new/problem/$', views.CreateProblemView.as_view(), name='create_problem'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/properties/$', views.UpdateFolderView.as_view(), name='folder_properties'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/delete/$', views.DeleteFolderView.as_view(), name='delete_folder'),
    url(r'^folders/(?P<folder_id_or_root>[0-9]+|root)/import-from-polygon/$', views.ImportFromPolygonView.as_view(), name='import_from_polygon'),

    url(r'^search/$', views.SearchView.as_view(), name='search'),

    url(r'^tex/$', views.TeXView.as_view(), name='tex_playground'),
    url(r'^tex/render/$', views.TeXRenderView.as_view(), name='tex_playground_render'),
]

project/solutions/urls.py
from django.conf.urls import include, url

from . import views

solutions_urlpatterns = [
    url(r'^$', views.SolutionListView.as_view(), name='list'),

    url(r'^(?P<solution_id>[0-9]+)/$', views.SolutionMainView.as_view(), name='main'),
    url(r'^(?P<solution_id>[0-9]+)/source/$', views.SolutionSourceView.as_view(), name='source'),
    url(r'^(?P<solution_id>[0-9]+)/log/$', views.SolutionLogView.as_view(), name='log'),
    url(r'^(?P<solution_id>[0-9]+)/tests/$', views.SolutionTestsView.as_view(), name='tests'),
    url(r'^(?P<solution_id>[0-9]+)/runs/$', views.SolutionJudgementsView.as_view(), name='judgements'),
    url(r'^(?P<solution_id>[0-9]+)/attempts/$', views.SolutionAttemptsView.as_view(), name='attempts'),
    url(r'^(?P<solution_id>[0-9]+)/plagiarism/$', views.SolutionPlagiarismView.as_view(), name='plagiarism'),
    url(r'^(?P<solution_id>[0-9]+)/status/json/$', views.SolutionStatusJsonView.as_view(), name='status_json'),

    url(r'^(?P<solution_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/$', views.SolutionTestCaseResultView.as_view(), name='test_case_result'),
    url(r'^(?P<solution_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/(?P<mode>input|output|answer|stdout|stderr)\.txt$', views.SolutionTestCaseResultDataView.as_view(), name='test_data'),
    url(r'^(?P<solution_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/images/(?P<filename>.*)$', views.SolutionTestCaseResultImageView.as_view(), name='test_image'),

    url(r'^(?P<solution_id>[0-9]+)/source/open/(?P<filename>.*)$', views.SolutionSourceOpenView.as_view(), name='source_open'),
    url(r'^(?P<solution_id>[0-9]+)/source/download/(?P<filename>.*)$', views.SolutionSourceDownloadView.as_view(), name='source_download'),

    url(r'^delete/$', views.DeleteSolutionsView.as_view(), name='delete'),

    url(r'^compare/$', views.CompareSolutionsView.as_view(), name='compare'),
]

judgements_urlpatterns = [
    url(r'^$', views.JudgementListView.as_view(), name='judgement_list'),
    url(r'^(?P<judgement_id>[0-9]+)/$', views.JudgementView.as_view(), name='show_judgement'),
    url(r'^(?P<judgement_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/$', views.JudgementTestCaseResultView.as_view(), name='judgement_testcaseresult'),
    url(r'^(?P<judgement_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/(?P<mode>input|output|answer|stdout|stderr)\.txt$', views.JudgementTestCaseResultDataView.as_view(), name='judgement_testdata'),
    url(r'^(?P<judgement_id>[0-9]+)/tests/(?P<testcaseresult_id>[0-9]+)/images/(?P<filename>.*)$', views.JudgementTestCaseResultImageView.as_view(), name='judgement_testimage'),
]

rejudges_urlpatterns = [
    url(r'^new/$', views.CreateRejudgeView.as_view(), name='create_rejudge'),
    url(r'^(?P<rejudge_id>[0-9]+)/$', views.RejudgeView.as_view(), name='rejudge'),
    url(r'^(?P<rejudge_id>[0-9]+)/status/json/$', views.RejudgeJsonView.as_view(), name='rejudge_status_json'),
    url(r'^$', views.RejudgeListView.as_view(), name='rejudge_list'),
]

challenges_urlpatterns = [
    url(r'^$', views.ChallengeListView.as_view(), name='challenge_list'),
]

urlpatterns = [
    url(r'^solutions/', include(solutions_urlpatterns)),
    url(r'^runs/', include(judgements_urlpatterns)),
    url(r'^rejudges/', include(rejudges_urlpatterns)),
    url(r'^challenges/', include(challenges_urlpatterns)),
]

project/solutions/templates/solutions/irunner_solutions_rejudgestate_tag.html
{% load i18n %}

{% if committed == True %}
    <span class="text-success">{% trans 'committed' %}</span>
{% elif committed == False %}
    <span class="text-danger">{% trans 'rolled back' %}</span>
{% else %}
    &mdash;
{% endif %}

project/solutions/templates/solutions/judgement_list.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_pagination %}
{% load irunner_solutions %}
{% load irunner_time %}

{% block title %}{% trans 'Runs' %}{% endblock %}

{% block content %}
    {% irunner_pagination pagination_context %}
    <table class="table table-condensed table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>{% trans 'Solution' %}</th>
                <th>{% trans 'Rejudge' %}</th>
                <th>{% trans 'Status' %}</th>
                <th>{% trans 'Created' %}</th>
                <th>{% trans 'In queue' %}</th>
                <th>{% trans 'Testing' %}</th>
            </tr>
        </thead>
        <tbody>
            {% for judgement in object_list %}
            <tr>
                <td><a href="{% url 'solutions:show_judgement' judgement.id %}">{{ judgement.id }}</a></td>
                <td><a href="{% url 'solutions:main' judgement.solution_id %}">{{ judgement.solution_id }}</a></td>
                <td>{% if judgement.rejudge_id %}<a href="{% url 'solutions:rejudge' judgement.rejudge_id %}">{{ judgement.rejudge_id }}</a>{% else %}&mdash;{% endif %}</td>
                <td class="text-nowrap">
                    {% irunner_solutions_judgementbox judgement tooltip=True %}
                    {% irunner_solutions_scorebox judgement %}
                </td>
                {% with judgement.extra_info as info %}
                    <td>
                        {% if info and info.creation_time %}
                            {{ info.creation_time }}
                        {% else %}
                            &mdash;
                        {% endif %}
                    </td>
                    <td>
                        {% if info %}
                            {% irunner_time_deltaseconds info.creation_time info.start_testing_time %}
                        {% else %}
                            &mdash;
                        {% endif %}
                    </td>
                    <td>
                        {% if info %}
                            {% irunner_time_deltaseconds info.start_testing_time info.finish_testing_time %}
                        {% else %}
                            &mdash;
                        {% endif %}
                    </td>
                {% endwith %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

project/solutions/templates/solutions/rejudge.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_problems %}
{% load irunner_proglangs %}
{% load irunner_progress %}
{% load irunner_solutions %}
{% load irunner_users %}

{% block content %}
    <h2>{% block title %}{% trans 'Rejudge' %} {{ rejudge.id }}{% endblock %}</h2>

    <dl class="dl-horizontal">
        <dt>{% trans 'Created' %}</dt>
        <dd>{{ rejudge.creation_time }}</dd>

        <dt>{% trans 'Author' %}</dt>
        <dd>{% irunner_users_show rejudge.author %}</dd>

        {% if problem %}
            <dt>{% trans 'Problem' %}</dt>
            <dd>{% irunner_problems_difficulty problem.difficulty %} <a href="{% url 'problems:statement' problem.id %}">{{ problem.numbered_full_name }}</a></dd>
        {% endif %}

        <dt>{% trans 'State' %}</dt>
        <dd>{% irunner_solutions_rejudgestate rejudge.committed %}</dd>

        <dt>{% trans 'Result' %}</dt>
        <dd>{% irunner_progress url=progress_url value_good=stats.accepted value_bad=stats.rejected total=stats.total %}</dd>
    </dl>

    {% if object_list %}
    <table class="table table-condensed">
        <thead>
            <tr>
                <th>{% trans '#' %}</th>
                <th>ID</th>
                <th>{% trans 'Submission time' %}</th>
                <th>{% trans 'Solution' %}</th>
                <th>{% trans 'Author' %}</th>
                <th>{% bootstrap_icon 'triangle-left' %} {% trans 'Before' %}</th>
                <th>{% bootstrap_icon 'triangle-right' %} {% trans 'After' %}</th>
                <th class="active">{% bootstrap_icon 'pause' %} {% trans 'Current' %}</th>
            </tr>
        </thead>
        <tbody>
            {% for info in object_list %}
            <tr>
                <td>
                    {{ forloop.counter }}
                </td>
                <td>
                    <a href="{% url 'solutions:main' info.solution.id %}">{{ info.solution.id }}</a>
                </td>
                <td>
                    {{ info.solution.reception_time }}
                </td>
                <td>
                    {% url 'solutions:source' info.solution.id as source_url %}
                    {% irunner_proglangs_compilerbox info.solution.compiler tooltip=True %}
                    <small><tt><a href="{{ source_url }}">{{ info.solution.source_code.filename }}</a></tt></small>
                </td>
                <td>
                    {% irunner_users_show info.solution.author %}
                </td>
                <td>
                    {% if info.before %}
                        <a href="{% url 'solutions:show_judgement' info.before.id %}">
                            {% irunner_solutions_judgementbox info.before tooltip=True %}{% irunner_solutions_scorebox info.before %}
                        </a>
                    {% endif %}
                </td>
                <td>
                    {% if info.after %}
                        <a href="{% url 'solutions:show_judgement' info.after.id %}">
                            {% irunner_solutions_judgementbox info.after tooltip=True %}{% irunner_solutions_scorebox info.after %}
                        </a>
                    {% endif %}
                </td>
                <td class="active">
                    {% if info.current %}
                        <a href="{% url 'solutions:show_judgement' info.current.id %}">
                            {% irunner_solutions_judgementbox info.current tooltip=True %}{% irunner_solutions_scorebox info.current %}
                        </a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="ir-absence">{% trans 'No solutions' %}</div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        {% buttons %}
            {% if rejudge.committed == None %}
                <button type="submit" name="commit" class="btn btn-primary">{% bootstrap_icon 'ok' %} <span class="ir-icon-label">{% trans 'Commit' %}</span></button>
                <button type="submit" name="rollback" class="btn btn-default">{% bootstrap_icon 'remove' %} <span class="ir-icon-label">{% trans 'Rollback' %}</span></button>
            {% endif %}
            <button type="submit" name="clone" class="btn btn-default">{% bootstrap_icon 'duplicate' %} <span class="ir-icon-label">{% trans 'Clone' %}</span></button>
        {% endbuttons %}
    </form>

    <p>
        <a href="{% url 'solutions:rejudge_list' %}">{% trans 'To the list of rejudges' %}</a>
    </p>
{% endblock %}

project/solutions/templates/solutions/solution.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_solutions %}
{% load irunner_problems %}
{% load irunner_proglangs %}
{% load irunner_users %}
{% load staticfiles %}

{% block title %}{% block subtitle %}{% trans 'Result' %}{% endblock %} &mdash; {% trans 'Solution' %} {{ solution.id }}{% endblock %}

{% block content %}
<div class="panel panel-default ir-solution-panel">
    <div class="panel-body">
        <h2>
            {% irunner_solutions_judgementbox solution.best_judgement tooltip=True complete=solution_permissions.state %}
            {% trans 'Solution' %} {{ solution.id }}
        </h2>
        <div class="row">
            <div class="col-md-6">
                <dl class="dl-horizontal">
                    <dt>{% trans 'Result' %}</dt>
                    <dd>{% irunner_solutions_judgementtext solution.best_judgement complete=solution_permissions.state %}</dd>

                    {% if solution_permissions.state and solution.best_judgement and not solution.stop_on_fail %}
                        <dt>{% trans 'Score' %}</dt>
                        <dd>{{ solution.best_judgement.score }} {% trans 'of' %} {{ solution.best_judgement.max_score }}</dd>
                    {% endif %}

                    <dt>{% trans 'Author' %}</dt>
                    <dd>{% irunner_users_card solution.author %}</dd>

                    {% if solution.problem %}
                        <dt>{% trans 'Problem' %}</dt>
                        {# What link to the problem is the best? #}
                        <dd>
                            {% if solution.problem.difficulty != None %}
                                {% irunner_problems_difficulty solution.problem.difficulty %}
                            {% endif %}
                            {% if user.is_staff %}
                                <a href="{% url 'problems:statement' solution.problem_id %}">{{ solution.problem.numbered_full_name }}</a>
                            {% elif solution_environment.course %}
                                <a href="{% url 'courses:course_problems_problem' solution_environment.course.id solution.problem_id %}">{{ solution.problem.numbered_full_name }}</a>
                            {% else %}
                                {# no link, just name #}
                                {{ solution.problem.numbered_full_name }}
                            {% endif %}
                        </dd>

                        <dt>{% trans 'Input&thinsp;/&thinsp;output' %}</dt>
                        <dd>{% irunner_problems_inputfile solution.problem.input_filename %}&thinsp;/&thinsp;{% irunner_problems_outputfile solution.problem.output_filename %}</dd>
                    {% endif %}

                    {% if solution_environment.course %}
                        <dt>{% trans 'Course' %}</dt>
                        <dd>
                            <a href="{% if solution.author == user %}{% url 'courses:my_solutions' solution_environment.course.id %}{% else %}{% url 'courses:all_solutions' solution_environment.course.id %}?user={{ solution.author.id }}{% endif %}">
                                {{ solution_environment.course }}
                            </a>
                        </dd>
                    {% endif %}

                    {% if solution_environment.contest %}
                        <dt>{% trans 'Contest' %}</dt>
                        <dd><a href="{% url 'contests:standings' solution_environment.contest.id %}">{{ solution_environment.contest }}</a></dd>
                    {% endif %}
                </dl>
            </div>

            <div class="col-md-6">
                <dl class="dl-horizontal">
                    <dt>{% trans 'Submitted' %}</dt>
                    <dd>{{ solution.reception_time }}</dd>

                    {% if extra_info and extra_info.finish_testing_time %}
                        <dt>{% trans 'Judged' %}</dt>
                        <dd>{{ extra_info.finish_testing_time }}</dd>
                    {% endif %}

                    {% if solution_permissions.ip_address and solution.ip_address %}
                        <dt>{% trans 'IP address' %}</dt>
                        <dd><span class="ir-monospace">{{ solution.ip_address }}</span></dd>
                    {% endif %}

                    <dt>{% trans 'File' %}</dt>
                    <dd>
                        <span class="ir-monospace">{{ solution.source_code.filename }}</span>
                        <span class="ir-file-size">({{ solution.source_code.size|filesizeformat }})</span>
                    </dd>

                    <dt>{% trans 'Compiler' %}</dt>
                    <dd>{% irunner_proglangs_compilerbox solution.compiler tooltip=False %} {{ solution.compiler }}</dd>
                </dl>
            </div>
        </div>
        <div class="row">
            <div class="span12 text-center">
                <ul class="nav nav-pills ir-solution-nav-pills">
                    {% if solution_permissions.attempts %}
                        <li role="presentation"{% if active_tab == 'attempts' %} class="active"{% endif %}>
                            <a href="{% url 'solutions:attempts' solution.id %}">{% trans 'Attempts' %} ({{ attempt_count }})</a>
                        </li>
                    {% endif %}

                    {% if solution_permissions.judgements %}
                        <li role="presentation"{% if active_tab == 'judgements' %} class="active"{% endif %}>
                            <a href="{% url 'solutions:judgements' solution.id %}">{% trans 'Judgements' %} ({{ judgement_count }})</a>
                        </li>
                    {% endif %}

                    {% if solution_permissions.source_code %}
                        <li role="presentation"{% if active_tab == 'source' %} class="active"{% endif %}>
                            <a href="{% url 'solutions:source' solution.id %}">{% trans 'Source code' %}</a>
                        </li>
                    {% endif %}

                    {% if solution_permissions.compilation_log %}
                        <li role="presentation"{% if active_tab == 'log' %} class="active"{% endif %}>
                            <a href="{% url 'solutions:log' solution.id %}">{% trans 'Compilation log' %}</a>
                        </li>
                    {% endif %}

                    {% if solution_permissions.sample_results or solution_permissions.results %}
                        <li role="presentation"{% if active_tab == 'tests' %} class="active"{% endif %}>
                            <a href="{% url 'solutions:tests' solution.id %}">{% trans 'Test results' %}</a>
                        </li>
                    {% endif %}

                    {% if solution_permissions.plagiarism %}
                        <li role="presentation"{% if active_tab == 'plagiarism' %} class="active"{% endif %}>
                            <a href="{% url 'solutions:plagiarism' solution.id %}">{% trans 'Plagiarism' %}</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% block main %}
{% endblock %}

{% endblock %}